import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, Text, View } from 'react-native';

import { createRole, deleteRole, getRoles, updateRole, updateRolePermissions } from '@/src/api/auth';
import { AppScreen } from '@/src/components/app-shell';
import { Button, Feedback, SectionHeader, Surface, TextField } from '@/src/components/ui';
import { parsePermissions, permissionGroups } from '@/src/lib/permissions';
import { palette, radius, spacing, typeScale } from '@/src/theme';
import type { Role } from '@/src/types/restaurant';

export default function RoleEditorScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const roleId = Number(id || 0); const editing = roleId > 0;
  const [role, setRole] = useState<Role | null>(null); const [name, setName] = useState(''); const [permissions, setPermissions] = useState<string[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [confirmDelete, setConfirmDelete] = useState(false);
  useEffect(() => { if (!editing) return; getRoles().then((response) => { const next = response.data.find((item) => item.ID === roleId) || null; setRole(next); setName(next?.display_name || next?.name || ''); setPermissions(parsePermissions(next?.permissions)); }).catch((err) => setError(err instanceof Error ? err.message : 'โหลดบทบาทไม่สำเร็จ')); }, [editing, roleId]);
  function toggle(key: string) { setPermissions((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]); }
  async function save() { if (!name.trim()) return; setSaving(true); setError(null); try { if (editing) { if (!role?.is_system) await updateRole(roleId, { display_name: name.trim() }); await updateRolePermissions(roleId, permissions); } else await createRole({ display_name: name.trim(), permissions }); router.back(); } catch (err) { setError(err instanceof Error ? err.message : 'บันทึกบทบาทไม่สำเร็จ'); } finally { setSaving(false); } }
  async function remove() { if (!confirmDelete) { setConfirmDelete(true); return; } setSaving(true); setError(null); try { await deleteRole(roleId); router.back(); } catch (err) { setError(err instanceof Error ? err.message : 'ลบบทบาทไม่สำเร็จ'); setSaving(false); } }
  return <AppScreen title={editing ? 'แก้ไขบทบาท' : 'เพิ่มบทบาท'} subtitle="กำหนดงานที่บทบาทนี้ทำได้ในร้าน" topLevel={false}>{error ? <Feedback title="ทำรายการไม่ได้" detail={error} tone="danger" /> : null}<Surface><SectionHeader title="ชื่อบทบาท" detail={role?.is_system ? 'บทบาทระบบเปลี่ยนชื่อไม่ได้ แต่ปรับสิทธิ์ได้' : undefined} /><TextField label="ชื่อที่แสดง" value={name} onChangeText={setName} /></Surface><Surface><SectionHeader title="สิทธิ์เริ่มต้น" detail={`${permissions.length} สิทธิ์ที่เลือก`} />{permissionGroups.map((group) => <View key={group.title} style={{ gap: spacing.sm }}><Text style={typeScale.cardTitle}>{group.title}</Text>{group.rows.map((row) => { const active = permissions.includes(row.key); return <Pressable key={row.key} onPress={() => toggle(row.key)} style={({ pressed }) => ({ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderWidth: 1, borderColor: active ? palette.primary : palette.borderStrong, borderRadius: radius.md, backgroundColor: active ? palette.primary : palette.surface, paddingHorizontal: spacing.md, opacity: pressed ? 0.75 : 1 })}><Text style={{ flex: 1, color: active ? palette.primaryText : palette.text, fontSize: 14, fontWeight: '600' }}>{row.label}</Text><Text style={{ color: active ? palette.primaryText : palette.muted }}>{active ? '✓' : ''}</Text></Pressable>; })}</View>)}</Surface><Surface><Button label={editing ? 'บันทึกบทบาท' : 'เพิ่มบทบาท'} onPress={save} loading={saving} />{editing && !role?.is_system ? <View style={{ flexDirection: 'row', gap: spacing.sm }}>{confirmDelete ? <Button variant="secondary" label="ยกเลิก" onPress={() => setConfirmDelete(false)} style={{ flex: 1 }} /> : null}<Button variant={confirmDelete ? 'danger' : 'secondary'} label={confirmDelete ? 'ยืนยันลบบทบาท' : 'ลบบทบาท'} onPress={remove} style={{ flex: 1 }} /></View> : null}</Surface></AppScreen>;
}
